version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: cmd/order_service/Dockerfile
    ports:
      - "8080:8080"

  payment-service:
    build:
      context: .
      dockerfile: cmd/payment_service/Dockerfile
    ports:
      - "8081:8081"

  product-service:
    build:
      context: .
      dockerfile: cmd/product_service/Dockerfile
    ports:
      - "8082:8082"

  user-service:
    build:
      context: .
      dockerfile: cmd/user_service/Dockerfile
    ports:
      - "8083:8083"
